### ISSUE TITLE
Supporting a project containing non elixir files

### ISSUE THREAD

**Issue by zachdaniel** [hrzndhrn/rewrite#15]
Hey there! I like the idea of having one central data structure to model programatic changes to an Elixir app, but it puts a wrinkle in my original plans to use this given that it expects to be able to parse all files as elixir files, even non-elixir files. Any thoughts on potentially making it support any file type, but only attempting to make the code/ast features available for elixir files?

**Comment by NickNeck** [comment]
I came to the same idea the some days ago. So, yes it is on my list for upcoming features. If you have some ideas for functions or API design in this topic, I am happy to hear from you.
