### ISSUE TITLE
Proposal: Error when saving source if file content has changed

### ISSUE THREAD

**Issue by zachallaun** [hrzndhrn/rewrite#18]
This is something I ran into with Mneme — if you ran your tests and let it hang during a prompt, then changed the file, then accepted the prompt, the content would be overwritten. I’m now [handling this](https://github.com/zachallaun/mneme/commit/da932555eab6033fc06f341438c8ec5959e2a0b4) by storing a hash of content in the source private map and comparing before saving, but I wonder if this is something that would make sense in Rewrite itself?

This would be a breaking change to both Sources and Projects. Source would store the hash of content on load, and then compare/update on save. Save would need to return the source instead of just :ok. 

Saving a project should update/save each source, and would also need to return the project on success and the project and failed saves on error (it currently returns failed saves, but not the project — since some could save, the project needs to be returned even on error).

I think there are good arguments to be made both to include and exclude this feature from Rewrite, but from a user’s perspective, silently overwriting changes is likely _not_ desired, so I thought I’d bring it up!

**Comment by NickNeck** [comment]
Great idea 👍 . In the current state or `rewrite` I am fine with breaking changes. I expecting there will come more breaking changes in the future. The issue #15 will also bring some breaking changes.

If you have time and desire a PR is welcome.

**Comment by zachallaun** [comment]
👍 I should be able to contribute a PR!

**Comment by zachallaun** [comment]
❤️ Thank you for working on this! Sorry that I didn't get to it myself.

**Comment by NickNeck** [comment]
@zachallaun no worries. There are coming some more breaking changes before this PR will be released with version 0.7.0. I have also forked `mneme` to test the `rewrite` changes directly with `mneme`.

**Comment by zachallaun** [comment]
Awesome, thank you! I saw #20 and agree with that change.
