### ISSUE TITLE
Updating a source with unformatted `:quoted` causes the quoted form to be overwritten

### ISSUE THREAD

**Issue by zachallaun** [hrzndhrn/rewrite#30]
[An issue was opened on Mneme](https://github.com/zachallaun/mneme/issues/53) that I think I've tracked down to a change that occurred during the 0.7.0 Rewrite refactor.

Here's the commit that fixed the bug in Mneme: https://github.com/zachallaun/mneme/commit/cd83a006b580f8cbc767041d1b6ecc91e7c92dc6

I'm not sure whether this behavior is desirable or not. On the one hand, it's nice that Rewrite keeps the quoted form and the content "in sync" -- on the other, if you're explicitly setting `:quoted`, it's unexpected that immediately calling `Source.get(source, :quoted)` could return something other than what you set.

**Comment by zachallaun** [comment]
[Here's where the offending code-path starts.](https://github.com/hrzndhrn/rewrite/blob/main/lib/rewrite/source.ex#L395-L401) The problem is that it all eventually leads back to `Rewrite.Source.Ex.handle_update(source, :content)` [here](https://github.com/hrzndhrn/rewrite/blob/main/lib/rewrite/source/ex.ex#L94-L96), which re-parses the quoted form.

**Comment by NickNeck** [comment]
The re-parsing is a desired behaviour. In `recode` I need this to detect issues at the right position when a previous task has changed the code. But you are also right that the behaviour is odd when we update a source with `:quoted` .
I will extend the docs and take a look if I can support both behaviours.

**Comment by NickNeck** [comment]
@zachallaun with version `0.10.0`, it is now possible to suppress the syncing of `:quoted` in `Source.Ex`. To do so, you have to change `Rewrite.new()` to `Rewrite.new([{Source.Ex, sync_quoted: false}])`.
