### ISSUE TITLE
formatting .ex files when a relevant `.formatter.exs` file is being changed or created

### ISSUE THREAD

**Issue by zachdaniel** [hrzndhrn/rewrite#33]
I spent quite some time trying to figure out how to "hack" this on top by finding and evaluating the relevant `.formatter.exs` file for each .ex source, and setting the formatter_opts. However, I ultimately couldn't figure out how to do this.

It seems like it could be a feature built into `rewrite`, or at least should potentially be supported. `put_formatter_opts` sets the formatter opts, but as far as I can tell those options are ultimately ignored.

Any ideas on how this could be implemented?

**Comment by NickNeck** [comment]
Hi @zachdaniel . Rewrite should respect the `.formatter` and overwrite opts with `put_formmater_opts`. So I think you have detect a bug. Could you give me a short example where it is not working?

I have made the following test:
```elixir
iex> alias Rewrite.Source
iex> code = """
...>     defmodule MyModule do
...>       import Bar
...>
...>       def foo(  x  ) do
...>         bar    x
...>       end
...>     end
...>  """
iex>  source |> Source.Ex.format() |> IO.puts()
defmodule MyModule do
  import Bar

  def foo(x) do
    bar(x)
  end
end

:ok
iex> source |> Source.Ex.put_formatter_opts(locals_without_parens: [bar: 1]) |> Source.Ex.format() |> IO.puts()
defmodule MyModule do
  import Bar

  def foo(x) do
    bar x
  end
end

:ok
iex> source |> Source.Ex.format(locals_without_parens: [bar: 1]) |> IO.puts()
defmodule MyModule do
  import Bar

  def foo(x) do
    bar x
  end
end
```
Do you use multiple `.formatter.ex` or just one at the root.

**Comment by zachdaniel** [comment]
what I'm getting at is that we're creating the `.formatter.exs` in the same `Rewrite` that is formatting files. Right now from what I can tell it gets the opts from `Mix.Tasks.Formatter.formatter_for_file` which (naturally) doesn't know about staged changes in rewrite.

**Comment by zachdaniel** [comment]
I'll see if I can work up a minimal reproduction :)

**Comment by zachdaniel** [comment]
I think you can experience the issue by calling `Rewrite.write_all`, as opposed to `Source.Ex.format`. From what I'm seeing, opts placed via `put_formatter_opts` are discarded at some point. If `put_formatter_opts` is respected, then I have some code I can use to crawl the sources, find and eval the relevant `.formatter.exs`, and replace the formatter opts myself :)

**Comment by NickNeck** [comment]
The function `Rewrite.write_all` does not formats the source it just writes anything at it is to disk.

**Comment by NickNeck** [comment]
Maybe something like the following code can help:
```elixir
    project = Rewrite.new!(["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"])

    # adding locals_without_parens
    project =
      Rewrite.update!(project, ".formatter.exs", fn source ->
        Source.update(source, :content, """
        # Used by "mix format"
        [
          inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
          locals_without_parens: [bar: 1]
        ]
        """)
      end)

    [formatter] =
      Enum.filter(project, fn source ->
        String.ends_with?(source.path, ".formatter.exs")
      end)

    {formatter_opts, _} = Source.get(formatter, :quoted) |> Code.eval_quoted()

    project
    |> Rewrite.map!(fn source ->
      formatted = Source.Ex.format(source, formatter_opts)
      Source.update(source, :content, formatted)
    end)
    |> Rewrite.write_all()
```
In this code the `.formatter.exs` will be updated and the new `formatter_opts` are used to update the project. The code needs the new version of rewrite I have released right now.

**Comment by zachdaniel** [comment]
Will take a look! I'll likely want to add some logic for ensuring that we're using the proper .formatter.exs for each file since a file uses its closest ancestor, but otherwise that makes sense 👍

**Comment by zachdaniel** [comment]
I do remember trying something along those lines and the formatter opts not being respected but I could have been making some other mistake. Will post here how it goes.

**Comment by zachdaniel** [comment]
Alright, was able to get it sorted, thanks for all your help :)
