### ISSUE TITLE
Extract TextDiff into it's own library?

### ISSUE THREAD

**Issue by bcardarella** [hrzndhrn/rewrite#36]
The TextDiff module is really nice, would it be possible to get that as it's own library?

**Comment by NickNeck** [comment]
That is possible. I will do it the next days if I find some time.

**Comment by bcardarella** [comment]
Awesome, thanks 😄

**Comment by NickNeck** [comment]
@bcardarella [TextDiff](https://hex.pm/packages/text_diff) is now available on hex.

**Comment by bcardarella** [comment]
Excellent, thank you :)
