### ISSUE TITLE
Should the DotFormatter code simply skip unknown dependencies?

### ISSUE THREAD

**Issue by zachdaniel** [hrzndhrn/rewrite#39]
One thing we do when testing igniter installers is we simply "run the installer" to see what patches it creates. Often, an installer will add itself as a dependency in the `.formatter.exs`. This currently makes `DotFormatter.read` fail, causing everything to use the default `.formatter.exs`. I think it might make more sense not to fail but to skip dependencies that couldn't be found.

This code here:

```elixir
  defp deps_paths(deps) do
    paths = Mix.Project.deps_paths()

    result =
      Enum.reduce_while(deps, [], fn dep, acc ->
        case Map.fetch(paths, dep) do
          :error -> {:halt, %DotFormatterError{reason: {:dep_not_found, dep}}}
          {:ok, path} -> {:cont, [{dep, Path.join(path, @default_dot_formatter)} | acc]}
        end
      end)

    if is_list(result), do: {:ok, result}, else: {:error, result}
  end
```

https://github.com/hrzndhrn/rewrite/blob/main/lib/rewrite/dot_formatter.ex#L1293

Could be adjusted instead to simply skip that dependency, perhaps logging some kind of warning? Alternatively, we could have some kind of option or flag we can set that tells it to ignore unknown dependencies.

Thoughts?

**Comment by NickNeck** [comment]
I think a flag `ignore_unknown_deps: true` would be the simplest solution. I will add such flag.

**Comment by zachdaniel** [comment]
Where would this action be specified? I think for all of igniter's cases we'd want that to be true, so just curious if its something we can set when creating with `Rewrite.new`

**Comment by zachdaniel** [comment]
I'd be willing to put a PR together if you can tell me where the "entry point" would be, as most of the projects's tests that are using rewrite through igniter will fail w/ this change. Its not a big deal, they are just tests failing around formatting, not the end of the world :) I also have some short term workarounds, I've added `Igniter.Project.Formatter.remove_imported_dep` which can be used in tests after installers run but before assertions are made if necessary.

**Comment by NickNeck** [comment]
I have added the `:ignore_unknown_deps` to `Rewrite.DotFormatter.read` and friends. So for `Rewrite.new` you can use `Rewrite.new(dot_formatter: DotFormatter.read!(ignore_unknown_deps: true))`. The `Rewrite.Hook.DotFormatterUpdater` has a fallback to a default `DotFormatter` if the reading fails.

Is that ok? If not, I can make further changes.

**Comment by zachdaniel** [comment]
I believe this will do just fine, yes :)

**Comment by zachdaniel** [comment]
Hmm...I think there might be a missing piece which is that the option should then be "retained" in some way by `Rewrite.Hook.DotFormatterUpdater` right? Or should I just write my own hook in that case?

**Comment by NickNeck** [comment]
Yes, I think to write `TestDotFormatterUpdate` should be work. I could also make the hooks configurable.

**Comment by zachdaniel** [comment]
I'll close this, please LMK if you get a sec when you release this @NickNeck

**Comment by NickNeck** [comment]
@zachdaniel the `ignore_unknown_deps` flag is released. Or do you mean the configurable hook?

**Comment by zachdaniel** [comment]
oh, I didn't realize! Thanks will check it out :)

**Comment by zachdaniel** [comment]
![CleanShot 2024-11-04 at 15 15 25@2x](https://github.com/user-attachments/assets/f4013b2d-313f-4005-ae9e-9530f1a6a0a3)
I had seen this on the home page and assumed :) Works, thanks!
