### ISSUE TITLE
Suppress line numbers in text diff

### ISSUE THREAD

**Issue by zachallaun** [hrzndhrn/rewrite#5]
Hi there!

I’m using Rewrite for an experimental testing library and would like the option to suppress line numbers when showing text diffs. Thinking a :line_numbers option defaulting to true would be just the ticket. If this is something you’re keen on, I’d be happy to submit a patch!

**Comment by NickNeck** [comment]
Hi @zachallaun . Sounds like a useful option. A PR is welcome.
