### ISSUE TITLE
Support some kind of patch-based workflow

### ISSUE THREAD

**Issue by zachallaun** [hrzndhrn/rewrite#6]
My use-case requires collecting a number of patches relative to the starting version of a source and then applying them all at once. Right now, however, that requires that I store these patches separately from a Source/Project struct, because applying them as I go requires updating the internal ast/code of the Source. 

I’m not sure what the API would look like. Basically I’d want to store patches with lines/cols relative to the latest version of the Source, and then “commit” them all at once, creating a new update and version.

**Comment by zachallaun** [comment]
Thinking through a possible API:

```elixir
Source.read!(“some_code.exs”)
|> Source.patch(…) # (1)
|> Source.patch(…) 
|> Source.patch(…)
|> Source.apply_patches() # (2)
```

After (1) and subsequent patches, the Source AST and code will be unchanged. After (2), all patches are applied and the new code is reparsed, creating a new version. 

The unanswered question to me is what happens if you try to update prior to applying patches. Any update could make the patches invalid — perhaps they’re marked as stale and ignored, but saved with the source? Or just deleted? Maybe you can somehow specify whether an update makes unapplied patches stale or not?

**Comment by NickNeck** [comment]
Hi @zachallaun 

My first thought on this is that it doesn't fit in `rewrite`. The lib does not care how the code will be transformed  it will just handle changes given to it. `apply_patches` would need some merge logic and this logic would be not so simple and would not fit to the strategy in `rewirte`. 

But I will think about it some more days.

What exactly should be achieved with the feature?

**Comment by zachallaun** [comment]
Sorry for taking so long to get back to you on this! I wanted to give it some more thought before replying, and I still haven't quite had time. In the meantime, I think it's fair to close this issue if you'd like and I'll re-open it later on if I come up with a compelling use-case.

**Comment by NickNeck** [comment]
I'll leave it open until we come up with an idea for it or rejecting it.

**Comment by zachallaun** [comment]
@NickNeck I had a thought about this.

What if instead of all the above, there was just an additional `:meta` field on `Source` that was a user-controlled map of data?

I realized that the primary reason I wanted the above was so that I could store all the data I need on the `Source` -- that way I can use `Project` etc. to manage sources and not have to keep around a secondary data structure that I index into to get whatever other data I need. If there was a `:meta` field on `Source`, I could just as easily stick a `:patches` list in there to support the above use-case.

**Comment by zachallaun** [comment]
Thinking through the API, the most future-proof thing is probably to require that metadata be put/read from a given key (arbitrary term). This would allow multiple libraries/contexts to use `source.meta`.

```elixir
iex> source = Source.read!("example.ex")
%Source{meta: %{}}

iex> source = Source.put_meta(source, :foo, :bar)
%Source{meta: %{foo: :bar}}

iex> source.meta[:foo]
:bar

# or perhaps
iex> Source.get_meta(source, :foo)
:bar
```

Edit: this is very similar to `Plug.Conn`'s `:private`: https://hexdocs.pm/plug/Plug.Conn.html#put_private/3

**Comment by NickNeck** [comment]
That looks like a good feature. A PR is welcome if you have time and desire.

**Comment by zachallaun** [comment]
Will submit shortly :)
